### PR TITLE
add plant photo placeholder, fix shadow

### LINKED ISSUE #22: fix plant card shadow

### LINKED ISSUE #24: add plant image in case no photo in plant card

### PR DESCRIPTION
**Pull request by marynag**

### CODE REVIEW

File: src/components/PlantCardPreview/PlantCardPreview.tsx [hunk 1]
```diff
@@ -30,13 +33,19 @@ export const PlantCardPreview = ({ plantInfo }: PlantCardPreviewProps) => {
 	const sizeText = `${minSize} - ${maxSize} cm`;
 	const wateringText = t(`components.watering.${watering}`);
 
-	//TODO: add photo template in  case no picture
+	const getPlantImagePlaceholder = () => {
+		const placeholderImages = [placeholderImage1, placeholderImage2, placeholderImage3];
+		const randomPlaceholderImage = placeholderImages[Math.floor(Math.random() * placeholderImages.length)];
+		const imageSource = photo?.urlPath || randomPlaceholderImage;
+		return Image.resolveAssetSource(imageSource).uri;
+	};
```
Comment (Taraslysak) [inline src/components/PlantCardPreview/PlantCardPreview.tsx]: I'd wrap this in `useMemo` hook

**Review by Taraslysak — COMMENTED** [review]
Good job
